import assert from "node:assert/strict";
import { readdir, readFile } from "node:fs/promises";
import test from "node:test";

const templateRoot = new URL("../", import.meta.url);

async function render() {
  // Vinext's Vercel preset emits the server entry under .vercel/output.
  // Keep this test aligned with the production artifact instead of the
  // legacy Cloudflare dist path that is no longer generated by the build.
  const workerUrl = new URL(
    "../.vercel/output/functions/__server.func/index.mjs",
    import.meta.url,
  );
  workerUrl.searchParams.set("test", `${process.pid}-${Date.now()}`);
  const { default: worker } = await import(workerUrl.href);

  return worker.fetch(
    new Request("http://localhost/", { headers: { accept: "text/html" } }),
    {
      ASSETS: {
        fetch: async () => new Response("Not found", { status: 404 }),
      },
    },
    {
      waitUntil() {},
      passThroughOnException() {},
    },
  );
}

test("server-renders the AgentFlow landing surface", async () => {
  const response = await render();
  assert.equal(response.status, 200);
  assert.match(response.headers.get("content-type") ?? "", /^text\/html\b/i);

  const html = await response.text();
  assert.match(html, /<title>AgentFlow — Connected commerce, made legible<\/title>/i);
  assert.match(html, /Turn Your Store Into an/i);
  assert.match(html, /Haven Home/i);
  assert.match(html, /Open Store/i);
  assert.doesNotMatch(html, /Your site is taking shape|react-loading-skeleton|codex-preview/i);
});

test("the source is the AgentFlow product rather than the starter placeholder", async () => {
  const [page, layout, workflow, customer, onboardingRoute, packageJson] = await Promise.all([
    readFile(new URL("../app/page.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/layout.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/merchant/workflow/WorkflowForm.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/customer/page.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/api/onboarding/compile/route.ts", import.meta.url), "utf8"),
    readFile(new URL("../package.json", import.meta.url), "utf8"),
  ]);

  assert.match(page, /MarketingApp/);
  assert.doesNotMatch(page, /Shop the customer demo/);
  assert.match(workflow, /Preview as customer/);
  assert.match(customer, /redirect\(shopifyPreviewStore\.url\)/);
  assert.doesNotMatch(customer, /Evaluate this offer|Connected customer demo/);
  assert.doesNotMatch(onboardingRoute, /compileDemoPolicyProposal|deterministic compiler used/i);
  assert.match(onboardingRoute, /NVIDIA Setup Copilot is unavailable/);
  assert.match(layout, /AgentFlow — Connected commerce, made legible/);
  assert.match(packageJson, /"vinext": "1\.0\.0-beta\.2"/);
  assert.match(packageJson, /"nitro":/);
  assert.deepEqual(await readdir(new URL("app/_sites-preview", templateRoot)), []);
});
