import { connectorCatalog } from "../../lib/connectors";
import { money } from "../../lib/catalogue";
import { MerchantShell, PageIntro, StatCard } from "./merchant-ui";

const events = [
  { label: "Offer allowed", detail: "Walnut Compact Desk · ₹12,500", time: "2m ago", tone: "success" as const },
  { label: "Approval requested", detail: "Bulk desk order · 20% requested", time: "7m ago", tone: "warning" as const },
  { label: "Policy boundary held", detail: "Untrusted proposal · no action taken", time: "11m ago", tone: "danger" as const },
];

export default function MerchantOverview() {
  return (
    <MerchantShell active="overview" title="Overview" description="A calm view of the commerce work your team has chosen to automate.">
      <PageIntro eyebrow="Wednesday, August 21, 2026" title="Your workspace is ready for a real customer loop." text="Start with the operating rules, then preview the separate storefront your customers will actually use." action={<a className="button button-dark" href="/customer">Open customer demo <span>↗</span></a>} />
      <div className="stats-grid"><StatCard label="Commerce sessions" value="1,284" detail="+23.1% over 7 days" tone="blue" /><StatCard label="Autonomous completion" value="72.8%" detail="Inside approved authority" tone="green" /><StatCard label="Merchant attention" value="8.4%" detail="Approval escalation rate" tone="peach" /><StatCard label="Preview GMV" value={money(284650)} detail="Connected demo volume" /></div>
      <div className="overview-grid"><section className="workspace-card activity-card"><div className="card-heading"><div><span className="section-label">Live commerce</span><h3>Recent activity</h3></div><a className="text-link" href="/merchant/activity">View activity <span>↗</span></a></div><div className="event-list">{events.map((event) => <div className="event-row" key={event.label}><span className={`event-icon event-${event.tone}`}>{event.tone === "danger" ? "!" : event.tone === "warning" ? "◌" : "✓"}</span><div><strong>{event.label}</strong><small>{event.detail}</small></div><time>{event.time}</time></div>)}</div><div className="card-footer"><span><i className="live-dot" />Updates in preview</span><a className="text-link" href="/merchant/activity">Open log</a></div></section><section className="workspace-card ready-card"><div className="card-heading"><div><span className="section-label">Your next step</span><h3>Make the workflow yours.</h3></div><span className="card-spark">✦</span></div><p>Choose the boundaries you want to test. The customer demo will use those values when you preview it.</p><a className="button button-dark button-full" href="/merchant/workflow">Configure workflow <span>↗</span></a><a className="text-link centered-link" href="/merchant/connectors">Review connected rails</a></section></div>
      <div className="overview-lower-grid"><a className="feature-card" href="/merchant/workflow"><span className="feature-number">01</span><span className="feature-tag">Workflow studio</span><h3>Define the safe range for every offer.</h3><p>Set discount, margin, inventory, and approval boundaries with a customer preview beside you.</p><span className="feature-link">Edit workflow ↗</span></a><a className="feature-card feature-card-soft" href="/merchant/catalog"><span className="feature-number">02</span><span className="feature-tag">Catalogue</span><h3>Keep product context close to the decision.</h3><p>See the connected products, inventory signals, and missing data that shape what the agent can do.</p><span className="feature-link">View catalogue ↗</span></a><div className="feature-card feature-card-dark"><span className="feature-number">03</span><span className="feature-tag">Customer surface</span><h3>Preview the other side of the conversation.</h3><p>Customers get their own destination, their own context, and a clear path to ask for help.</p><a className="feature-link" href="/customer">Open customer demo ↗</a></div></div>
      <section className="connector-strip"><div><span className="section-label">Connected rails</span><h3>Everything has a home.</h3></div><div className="connector-strip-items">{connectorCatalog.slice(0, 3).map((connector) => <div key={connector.name}><span className="connector-mini-icon">{connector.icon}</span><div><strong>{connector.name}</strong><small>{connector.status}</small></div></div>)}</div><a className="text-link" href="/merchant/connectors">Manage <span>↗</span></a></section>
    </MerchantShell>
  );
}
