import type { Product } from "./policy";

export const products: Product[] = [
  {
    id: "desk-032",
    sku: "DESK-032",
    name: "Walnut Compact Desk",
    category: "Desks",
    price: 13499,
    cost: 9280,
    stock: 43,
    finish: "Walnut",
    material: "Solid ash veneer",
    width: 110,
    description: "A quiet, compact desk with a warm walnut finish and a cable slot built for small rooms.",
    art: "walnut",
    tag: "Best fit",
  },
  {
    id: "desk-017",
    sku: "DESK-017",
    name: "Dark Oak Writing Desk",
    category: "Desks",
    price: 11999,
    cost: 7740,
    stock: 74,
    finish: "Dark oak",
    material: "Oak veneer",
    width: 120,
    description: "A clean-lined work surface with a little more room to spread out.",
    art: "oak",
    tag: "Good value",
  },
  {
    id: "desk-041",
    sku: "DESK-041",
    name: "Aster Lean Desk",
    category: "Desks",
    price: 14999,
    cost: 10100,
    stock: 18,
    finish: "Smoked walnut",
    material: "Walnut veneer",
    width: 100,
    description: "A slim profile for tighter corners, with a darker finish and hidden storage.",
    art: "smoke",
    tag: "Minimal profile",
  },
  {
    id: "chair-006",
    sku: "CHAIR-006",
    name: "Loom Desk Chair",
    category: "Chairs",
    price: 7499,
    cost: 4600,
    stock: 9,
    finish: "Charcoal",
    material: "Woven cotton",
    width: 58,
    description: "A supportive dining-height chair with a soft woven back.",
    art: "charcoal",
    tag: "Low stock",
  },
  {
    id: "lamp-022",
    sku: "LAMP-022",
    name: "Brass Arc Lamp",
    category: "Lamps",
    price: 4299,
    cost: 2010,
    stock: 121,
    finish: "Brushed brass",
    material: "Powder-coated steel",
    width: 32,
    description: "Warm, directional light with a sculptural profile for a desk or reading corner.",
    art: "brass",
    tag: "High stock",
  },
  {
    id: "accessory-014",
    sku: "ACC-014",
    name: "Leather Cable Tray",
    category: "Accessories",
    price: 1299,
    cost: 530,
    stock: 168,
    finish: "Cognac",
    material: "Vegetable-tanned leather",
    width: 32,
    description: "A small, useful upgrade that keeps cables off the floor and out of sight.",
    art: "cognac",
    tag: "Bundle ready",
  },
];

export const money = (amount: number) => `₹${Math.round(amount).toLocaleString("en-IN")}`;
